version: '3.7'
services:
  timescaledb:
    image: polokuro/timescaledb-debezium:0.0.1
    container_name: timescaledb3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=benchmark
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    logging:
      driver: none
  # debezium:
  #   image: debezium/connect:1.8
  #   container_name: debezium1
  #   environment:
  #     BOOTSTRAP_SERVERS: redpanda:9092
  #     GROUP_ID: 1
  #     CONFIG_STORAGE_TOPIC: connect_configs
  #     OFFSET_STORAGE_TOPIC: connect_offsets
  #     STATUS_STORAGE_TOPIC: connect_status
  #     KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
  #     VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
  #     CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  #     CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  #   depends_on: [redpanda]
  #   ports:
  #     - 8083:8083
  #   logging:
  #     driver: none
  kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    container_name: kafka-connect
    depends_on:
      - redpanda
      - schema-registry
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "redpanda:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status

      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'

      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'

      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      # CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
    # #  ---------------
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
    # # If you want to use the Confluent Hub installer to d/l component, but make them available
    # # when running this offline, spin up the stack once and then run : 
    # #   docker cp kafka-connect:/usr/share/confluent-hub-components ./data/connect-jars
    volumes:
      - ./data:/data
      - ./properties/:/properties/
    # In the command section, $ are replaced with $$ to avoid the error 'Invalid interpolation format for "command" option'
    command:
        # /etc/confluent/docker/run &
      - bash
      - -c
      - |
        echo "Installing Connector"
        confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest
        #
        echo "Launching Kafka Connect worker"
        /bin/connect-standalone /properties/worker-sink-postgres-trades-upsert.properties /properties/connector-sink-postgres-trades-upsert.properties
        #
        sleep infinity
  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.3
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=redpanda:29092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081,http://localhost:8081
    ports:
      - 8081:8081
    depends_on: [redpanda]
    logging:
      driver: none
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop4
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "redpanda2:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "redpanda"
    logging:
      driver: none
  redpanda:
    # image: vectorized/redpanda:v21.6.1
    image: vectorized/redpanda:latest
    container_name: redpanda2
    entrypoint:
      - /usr/bin/rpk
      - redpanda
      - start
      - --smp=2
      - --memory=4G
      - --overprovisioned
      - --default-log-level=info
      - --node-id=0
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,DOCKER://redpanda:9092,OUTSIDE://redpanda:9093
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,DOCKER://redpanda:9092,OUTSIDE://127.0.0.1:9093
    ports:
      - 9092:9092
      - 9093:9093
      - 29092:29092
    volumes:
      - /var/lib/redpanda2/data:/var/lib/redpanda2/data
    logging:
      driver: none
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   logging:
  #     driver: none